### ISSUE TITLE
As a developer, I need to set up a Raspberry Pi for development and sensor input.

### ISSUE THREAD

**Issue by iandouglas** [My-Solar-Garden/hardware#1]
- format the SD card and install the OS
- set it up on wifi
- maybe install some Ruby or Python libraries as appropriate

- [ ] readme updated

**Comment by leahriffell** [comment]
Should this one be closed? @lkriffell @moosehandlr @AngelaGuardia

**Comment by AngelaGuardia** [comment]
I'm gonna go ahead and close it.
